contact:
  phone_number: (657) 278-2387
  email: gbest@fullerton.edu
  vcard_path: ../assets/

site:
  vitae_path: ../assets/
  csuf_url: http://www.google.com
  copyright_text: Â© Copyright 2016 Gabriela Best.  All rights reserved